### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hasanbalci** [sciluna/cytoscape.js-sbgn-layout#1]
- [x] Support for non-nested chain like graphs ([sample](https://github.com/sciluna/cytoscape.js-sbgn-layout/blob/main/demo/images/glycolysis.png?raw=true))
- [ ] Support for non-nested more complex graphs ([sample](https://github.com/sciluna/cytoscape.js-sbgn-layout/blob/main/demo/images/TCA%20cycle.png?raw=true))
- [ ] Support for cycles
- [ ] Support for multiple level of nesting 
  - [x] Complex nodes ([sample](https://github.com/sciluna/cytoscape.js-sbgn-layout/blob/main/demo/images/Beta_oxidation_of_hexanoyl-CoA_to_butanoyl-CoA.png?raw=true))
  - [ ] Compartments with inter-graph edges ([sample](https://github.com/sciluna/cytoscape.js-sbgn-layout/blob/main/demo/images/neuronal_muscle_signaling.png?raw=true))
- [ ] Improved polishing (for the placement of one-degree nodes without node overlap)
- [x] Incremental layout support
- [ ] Test LLMs for aspect ratio constraint
